### ISSUE TITLE
Polygon buffer option does not produce a right polygon using a distance of 100 meters using projections defined in this library

### ISSUE THREAD

**Issue by fgfernandez0321** [jswhit/pyproj#107]
## Expected behavior and actual behavior.
I expected to get the same distance when I will convert Mercator to Earth projection, in this case 100 meters

## Steps to reproduce the problem.
Initial Coordinates: [{lat: 25.683358829506474, lng: -80.27368442285156}, {lat: 25.680767547232723, lng: -80.27368442285156}, {lat: 25.680767547232723, lng: -80.2708090947876}, {lat: 25.683358829506474, lng: -80.2708090947876}, {lat: 25.683358829506474, lng: -80.27368442285156}]

Scaled Coordinates using buffer function: [{lat: 25.684168391105594, lng: -80.27458273816451}, {lat: 25.684168391105594, lng: -80.26991077951816}, {lat: 25.6799579625669, lng: -80.26991077951816}, {lat: 25.6799579625669, lng: -80.27458273816451}, {lat: 25.684168391105594, lng: -80.27458273816451}]

1. Create projections
earth_projection = pyproj.Proj(init='EPSG:4326')
mercator_projection = pyproj.Proj(init='EPSG:3857')

earth_to_mercator_projection = partial(pyproj.transform, earth_projection, mercator_projection)
mercator_to_earth_projection = partial(pyproj.transform, mercator_projection, earth_projection)

2. Create Polygon using Initial Coordinates where latitude and longitude are used inverse
**polygon** = Polygon(Initial Coordinates)

3. Project polygon using transform function: Earth to Mercator
**transformed_model** = shapely.transform(earth_to_mercator_projection, **polygon**)

4. Buffer transformed model with 100 meters
**b_model_area** = **transformed_model**.buffer(distance=100, cap_style=2, join_style=2)

5. Project **b_model_area** using  transform function: Mercator to Earth
**final_shape** = shapely.transform(mercator_to_earth_projection, **b_model_area**)

So, I represented these shapes in Google Maps (Initial Shape: Polygon generated in step 2 and Final Shape: Polygon generated in step 5). When I calculate distance between corners (horizontal and vertical), the result is 90 meters instead of 100 meters defined at the beginning. The result is the same if I defined: 

**mercator_projection** = pyproj.Proj('+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs')

![screenshot from 2017-03-22 20-09-13](https://cloud.githubusercontent.com/assets/10324741/24226703/545a3c16-0f3e-11e7-8e34-ba7ce371c6b3.png)

Horizontal and Vertical Distances are 90 instead of 100 meters.

![screenshot from 2017-03-22 20-31-37](https://cloud.githubusercontent.com/assets/10324741/24226738/93c4e11c-0f3e-11e7-8b7f-e230ab26523b.png)

## Operating system
Ubuntu 16.04.2 LTS

## Shapely version and provenance
Version 1.5.13

**Comment by micahcochran** [comment]
What you are calling "Earth Projection"  is called WGS84 coordinate system (EPSG:4326), which is a pretty default GIS Coordinate system, which is basically a type of Mercator projection. The "Mercator projection"  is the Web Auxiliary Mercator projection, which actually even less accurate than WGS84 because it assumes the earth is a sphere (instead of using an ellipsoid).

Mercator-like projections aren't good for distances or areas.  The obvious example for Mercator projection is that Greenland looks bigger than Africa, when in reality Africa is 14 times the size.  However, The strength of these projections is the direction of north is up on the map and that 90 degree angled intersections look square on the map.

Converting between two projections that do not do distance well seems problematic.

If you convert these lat/longs to Florida East State Plane coordinate system (EPSG:3511) do your buffering and then distance calculation, it should reduce much of the distortion.  Even UTM Zone 17 North projection would have only slightly more distortion than the State Plane coordinate system.   These are projections that only try to accurately give a coordinate system for a small portion of the earth, which is also a compromise.

You have to be really aware of what algorithms you are using to compute distance and area when you are using a Mercator-like projection.

**Comment by fgfernandez0321** [comment]
Hello, 
I tested again using your suggestions and it is much better now. 

Thank you for your help.

**Comment by micahcochran** [comment]
Glad that I could be of some help.
