### ISSUE TITLE
Not converting between two custom crs

### ISSUE THREAD

**Issue by brunorpinho** [jswhit/pyproj#108]
I have no clue why this is not converting between these two different projections.
```
from pyproj import Proj, transform

CA_geo_Proj = Proj('+proj=latlong +a=6378388.0 +b=6356912.0 +rf=297.000745017694  +no_defs')
sirgas_Proj = Proj('+proj=latlong +a=6378137.0 +b=6356752.314140 +rf=298.257221538149 +no_defs')

x1, y1 = (-53.739868, -31.495987)
x2, y2 = transform(CA_geo_Proj, sirgas_Proj,x1,y1)
print (x2, y2)
```

Output: -53.739868 -31.495987
Which is not correct.

Any ideas? Am I doing something wrong?

**Comment by micahcochran** [comment]
One quick point, these are actually just two different datums of the size and shape of the ellipsoid.  Both projections are `latlong`.

My output from running that:
```Python
(-53.739868, -31.495986999999996)
```
I have no idea if that is what it should be.

These output should be close because you have just changed the earth datum slightly.  `+a`, `+b`, and `+rf` are used to determine the shape of the ellipsoid.  Only two are needed.  My guess without looking at the code is that it uses the first two parameters (`+a` and `+b`) and ignores the rest(`+rf`).

If you are working with [Brazilian Coordinate Reference Systems see this](https://wiki.osgeo.org/wiki/Brazilian_Coordinate_Reference_Systems)

You might want to install [certain grids](http://proj4.org/grids.html#brazil) that adjust the coordinates to for better accuracy.

If there is an EPSG code for the coordinate system, you might try to use that.

It looks like there was an [issue with proj4 about how to handle Brazillian coordinate systems](https://github.com/OSGeo/proj.4/issues/241).  I would assume that the current pyproj release should have resolved that.

**Comment by brunorpinho** [comment]
Thank you very much, Micah!

I can transform the coordinates by using the EPSG from 4225 (Córrego Alegre) to 31982 (SIRGAS 2000 UTM 22S), but the problem is that I prefer to use a custom SIRGAS 2000 CRS because we identified that PROJ.4 considers SIRGAS 2000 to be identical do WGS84 (Source: [From your link](https://wiki.osgeo.org/wiki/Brazilian_Coordinate_Reference_Systems), but they are not. 

They use the same ellipsoid, but their parameters have a subtle difference that may cause some problems when working with high accuracy.

Shape parameters from WGS84:
`+a=6378137.0 +b=6356752.314245 +rf=298.257223563`

Shape parameters for SIRGAS 2000:
`+a=6378137.0 +b=6356752.314140 +rf=298.257221538149`

The EPSG code for Córrego Alegre is working. I just can't figure out why my custom SIRGAS 2000 projection to work.
