### ISSUE TITLE
Type error (used to work):

### ISSUE THREAD

**Issue by citibeth** [jswhit/pyproj#53]
Consider the following code:
```
	xyproj = pyproj.Proj(sproj)
	llproj = xyproj.to_latlong()
	print(type(xyproj))
	print(type(llproj))
	ondata, latdata = pyproj.transform(self.xyproj, self.llproj, xdata, ydata)
```

This used to work.  But now, it gives me the following:

```
<class 'pyproj.Proj'>
<class '_proj.Proj'>
Traceback (most recent call last):
  File "plot_grid_outlines.py", line 27, in <module>
    grid1.plot(basemap)
  File "/Users/rpfische/git/icebin/pylib/icebin.py", line 125, in plot
    londata, latdata = pyproj.transform(self.xyproj, self.llproj, xdata, ydata)
  File "/Users/rpfische/macports/mpgompi-4.9.3/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyproj/__init__.py", line 494, in transform
    raise TypeError("p2 must be a Proj class")
TypeError: p2 must be a Proj class
```
Why is llproj not of the same type as xyproj?  And why is transform() now giving an error?

Thanks,
-- Elizabeth

**Comment by micahcochran** [comment]
I submitted a patch a couple month ago that apparently tightens typechecking down a bit too much.  _proj.Proj is the Cython code which communicates with the C Proj.4 library.  I think there is enough information for the transform() to be able to run using either class.

The way to quickly fix this is to comment out these lines (491-494) under the transform function.
```Python
    # check that p1 and p2 are from the Proj class
    if not isinstance(p1, Proj):
        raise TypeError("p1 must be a Proj class")
    if not isinstance(p2, Proj):
        raise TypeError("p2 must be a Proj class")
```

[If you can, test this patch](https://github.com/micahcochran/pyproj/tree/typechecking) where I think I have fixed the problem.

Before I submit a pull request, I would like to make a unit test out of this, so that this doesn't get broken again in the future.  The code that you gave has a couple of undefined variables, but I got the gist of it. @citibeth Can you help with creating a sample for a unit test for the problem?

**Comment by georgeouzou** [comment]
@micahcochran i think you can check only for the base class in the patch like this:
 ``` 
    if not isinstance(p1, _proj.Proj):
        raise TypeError("p1 must be a Proj class")
    if not isinstance(p2, _proj.Proj):
        raise TypeError("p2 must be a Proj class")
```
But the function **to_latlong** should really return a pyproj.Proj instance and not the underlying base instance. I will try to make a patch for this

**Comment by citibeth** [comment]
The patch works for me.  Here's a sample program.  I don't know what the results SHOULD be, so this isn't a quantitative test of correctness.  But it does show that the program runs.

```
import pyproj
import numpy as np
import sys

sproj = u'+proj=stere +lon_0=-39 +lat_0=90 +lat_ts=71.0 +ellps=WGS84'

xyproj = pyproj.Proj(sproj)
llproj = xyproj.to_latlong()

#print(type(xyproj))
#print(type(llproj))

km=1000.
xdata = np.array([100*km, 200*km])
ydata = np.array([600*km, 400*km])

print(xdata)
print(ydata)

londata, latdata = pyproj.transform(xyproj, llproj, xdata, ydata)

print(londata)
print(latdata)
```

**Comment by micahcochran** [comment]
@citibeth Thanks I can work with that.  The most important thing is that the TypeException doesn't get raised again.  With regard to whoever patches it.

@georgeouzou Good point about the base class. If you want to work on that patch, go for it.

**Comment by micahcochran** [comment]
PR #73 merged fixing this.  Closing.
